import { skillsDetailsPops } from "@/types/allTypes";

export const skillsDetails: skillsDetailsPops[] = [
  {
    id: "JEST",
    alt: "JEST LOGO SVG",
    title: "jest",
    icon: "Jest",
    features: [
      "unit testing",
      "test Runner",
      "test File Structure",
      "test coverage",
      "mocking",
      "test Structure",
      "assertions",
      "snapshot testing",
      "user-centric testing",
      "rendering",
      "querying",
      "user actions",
      "data-testing",
    ],
  },
  {
    id: "HTML",
    alt: "HTML LOGO SVG",
    title: "html",
    icon: "Html",
    features: [
      "semantic HTML",
      "technical SEO",
      "core web vitals",
      "elememts / attributes",
      "forms / input types",
      "imports / META tags",
      "lists / anchor",
      "tables",
      "events",
      "webstorage",
      "images / multimedia",
      "frame",
      "canvas / SVG",
      "frame",
      "performance",
      "accessibility",
      "best practices",
    ],
  },
  {
    id: "CSS",
    alt: "CSS LOGO SVG",
    title: "css",
    icon: "Css",
    features: [
      "selectors(basic/complex)",
      "Psuedo selectors",
      "specificity / inheritance",
      "Box model",
      "typography",
      "positions / units / display",
      "Layout : Flex / Grid",
      "responsive design",
      "shadows",
      "colors / gradiants",
      "transforms / transition",
      "animations",
      "Media queries",
      "CSS varibles",
      "BEM",
    ],
  },
  {
    id: "TS",
    alt: "TS LOGO SVG",
    title: "typescript",
    icon: "Typescript",
    features: [
      "static Typing",
      "type annotations",
      "type Inference",
      "interfaces",
      "functions",
      "classes",
      "type aliases",
    ],
  },
  {
    id: "SASS",
    alt: "SASS LOGO SVG",
    title: "sass",
    icon: "Sass",
    features: [
      "varibles",
      "mixin",
      "nested style",
      "data iterate",
      "functions",
      "operators",
      "partials",
      "inheritance",
      "imports",
      "best practices",
    ],
  },
  {
    id: "TAILWIND",
    alt: "TAILWIND LOGO SVG",
    title: "tailwind",
    icon: "Tailwind",
    features: [
      "utility first",
      "responsive design",
      "classes are modifiers",
      "customization",
      "configs",
      "typography",
      "dark mode",
      "spacing",
      "layout",
      "colors",
      "borders",
      "forms",
      "...",
    ],
  },
  {
    id: "MUI",
    alt: "MATERIAL LOGO SVG",
    title: "material ui",
    icon: "Mui",
    features: [
      "MUI fundamentals",
      "Responsive pattern",
      "components",
      "hooks",
      "styles",
      "themes",
      "Data grid",
      "Docs",
    ],
  },
  {
    id: "JS",
    alt: "JAVASCRIPT LOGO SVG",
    title: "javascript",
    icon: "Js",
    features: [
      "varibles & primitives",
      "scope / hoisting",
      "operators / type conversions",
      "closures",
      "objects / methods",
      "arrays / methods",
      "functions / arrow funtions",
      "timeoute / interval",
      "mudules",
      "classes / proxies",
      "ES6 / syntaxes",
      "prototypes",
      "iterators / iterables",
      "destructuring / spread",
      "THIS keyword",
      "callbacks / promise",
      "async await",
    ],
  },
  {
    id: "WEBPACK",
    alt: "WEBPACK LOGO SVG",
    title: "webpack",
    icon: "Webpack",
    features: [
      "configs for bundling",
      "entry / output",
      "loaders",
      "plugins",
      "chunks",
      "HTML plugin",
      "CSS plugin",
      "dev server / production",
      "webpack config",
    ],
  },
  {
    id: "REACT",
    alt: "REACT JS LOGO SVG",
    title: "react js",
    icon: "React",
    features: [
      "fundamentals",
      "component-based architecture",
      "functional components",
      "class components",
      "JSX syntax",
      "react hooks",
      "custom hooks",
      "HOC",
      "props",
      "state managment",
      "virtual DOM",
      "event handling",
      "forms",
      "routing",
      "conditional rendering",
      "client-side fetch",
      "declarative style",
      "performance optimization",
    ],
  },
  {
    id: "REDUX",
    alt: "REDUX LOGO SVG",
    title: "redux",
    icon: "Redux",
    features: [
      "fundamentals",
      "store",
      "action",
      "reducers",
      "selectors",
      "redux thunk",
      "redux toolkit",
      "RTK",
      "integration",
      "extra reducers",
      "best practices",
    ],
  },
  {
    id: "NODE",
    alt: "NODE JS LOGO SVG",
    title: "node js",
    icon: "Node",
    features: [
      "basic familarity",
      "creating server",
      "connecting to db",
      "cors",
      "ENV",
      "integretion with express",
    ],
  },
  {
    id: "EXPRESS",
    alt: "EXPRESS JS LOGO SVG",
    title: "express js",
    icon: "Express",
    features: [
      "faster server side development",
      "REST api",
      "middleware",
      "Routing",
      "Templating",
      "Debugging",
    ],
  },
  {
    id: "MONGODB",
    alt: "MONGO DB LOGO SVG",
    title: "mongoDB",
    icon: "Mongodb",
    features: [
      "fundamentals",
      "CRUD operation",
      "indexing",
      "querys",
      "data model",
      "data types",
      "mongodb atlas",
      "mongoose",
    ],
  },
  {
    id: "NEXT",
    alt: "NEXT JS LOGO SVG",
    title: "next js",
    icon: "Next",
    features: [
      "Server-side rendering (SSR)",
      "Static site generation (SSG)",
      "Incremental static regeneration (ISR)",
      "Image optimization",
      "Routing",
      "Dynamic routing",
      "Data fetching",
      "Server actions",
    ],
  },
  {
    id: "GIT",
    alt: "GIT LOGO SVG",
    title: "git",
    icon: "Git",
    features: [
      "version control",
      "branching and merging",
      "staging and committing",
      "pushing and pulling",
      "collaboration",
      "merge and rebase",
      "resolving conflicts",
    ],
  },
  {
    id: "XD",
    alt: "ADOBE XD LOGO SVG",
    title: "adobe XD",
    icon: "Xd",
    features: [
      "fundamentals",
      "assets",
      "components",
      "prototypes",
      "exporting design to code",
    ],
  },
  {
    id: "AI",
    alt: "ADOBE ILLUSTRATOR LOGO SVG",
    title: "a-illustrator",
    icon: "Ai",
    features: [
      "basic familarity",
      "basic tools",
      "complex shape and logo design",
    ],
  },
  {
    id: "AE",
    alt: "ADOBE AFTER EFFECT LOGO SVG",
    title: "a-aftrer effects",
    icon: "Ae",
    features: [
      "fundamentals",
      "basic tools",
      "motion tracking",
      "masking",
      "simple projects",
    ],
  },
];
