export const skillsDetails = [
  {
    id: "JEST",
    alt: "JEST LOGO SVG",
    title: "JEST",
    icon: "Jest",
    description: "HTML asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "unit testing",
      "integration testing",
      "end-to-end testing",
      "test coverage",
      "mocking",
      "stubbing",
    ],
  },
  {
    id: "HTML",
    alt: "HTML LOGO SVG",
    title: "HTML",
    icon: "Html",
    description: "HTML asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "semantic HTML",
      "technical SEO",
      "elememts / attributes",
      "forms / input types",
      "imports / META tags",
      "lists / anchor",
      "tables",
      "events",
      "webstorage",
      "images / multimedia",
      "frame",
      "canvas / SVG",
      "frame",
    ],
  },
  {
    id: "CSS",
    alt: "CSS LOGO SVG",
    title: "CSS",
    icon: "Css",
    description: "CSS asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "selectors(basic/complex)",
      "Psuedo selectors",
      "specificity / inheritance",
      "Box model",
      "typography",
      "positions / units / display",
      "Layout : Flex / Grid",
      "responsive design",
      "shadows",
      "colors / gradiants",
      "transforms / transition",
      "animations",
      "Media queries",
      "CSS varibles",
      "BEM",
    ],
  },
  {
    id: "TS",
    alt: "TS LOGO SVG",
    title: "TYPESCRIPT",
    icon: "Typescript",
    description: "CSS asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "type annotations",
      "type inference",
      "interfaces",
      "generics",
      "enums",
      "decorators",
      "namespaces",
      "modules",
      "ambient declarations",
    ],
  },
  {
    id: "SASS",
    alt: "SASS LOGO SVG",
    title: "SASS",
    icon: "Sass",
    description: "Js  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "Nested style",
      "Mixin",
      "Varibles",
      "Data iterate",
      "Best practices",
    ],
  },
  {
    id: "TAILWIND",
    alt: "TAILWIND LOGO SVG",
    title: "TAILWIND",
    icon: "Tailwind",
    description: "React  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "tailwind classes",
      "just-in-time compiling",
      "custom components",
      "variants",
      "plugins",
      "dark mode",
      "accessibility",
      "performance",
      "testing",
    ],
  },
  {
    id: "MUI",
    alt: "MATERIAL LOGO SVG",
    title: "MATERIAL UI",
    icon: "Mui",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "MUI fundamentals",
      "Responsive pattern",
      "components",
      "hooks",
      "styles",
      "themes",
      "Data grid",
      "Docs",
    ],
  },
  {
    id: "JS",
    alt: "JAVASCRIPT LOGO SVG",
    title: "JAVASCRIPT",
    icon: "Js",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "varibles & primitives",
      "scope / hoisting",
      "operators / type conversions",
      "closures",
      "objects / methods",
      "arrays / methods",
      "functions / arrow funtions",
      "timeoute / interval",
      "mudules",
      "classes / proxies",
      "ES6 / syntaxes",
      "prototypes",
      "iterators / iterables",
      "destructuring / spread",
      "THIS keyword",
      "callbacks / promise",
      "async await",
    ],
  },
  {
    id: "WEBPACK",
    alt: "WEBPACK LOGO SVG",
    title: "WEBPACK",
    icon: "Webpack",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "configs for bundling",
      "entry / output",
      "loaders",
      "plugins",
      "chunks",
      "HTML plugin",
      "CSS plugin",
      "dev server / production",
      "webpack config",
    ],
  },
  {
    id: "REACT",
    alt: "REACT JS LOGO SVG",
    title: "REACT JS",
    icon: "React",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "fundamentals",
      "functional components",
      "class components",
      "JSX",
      "react hooks",
      "custom hooks",
      "HOC",
      "props",
      "state managment",
      "routes",
      "auth",
      "client-side fetch",
    ],
  },
  {
    id: "REDUX",
    alt: "REDUX LOGO SVG",
    title: "REDUX",
    icon: "Redux",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "fundamentals",
      "store",
      "action creators",
      "reducers",
      "redux toolkit",
      "extra reducers",
      "best practices",
    ],
  },
  {
    id: "NODE",
    alt: "NODE JS LOGO SVG",
    title: "NODE JS",
    icon: "Node",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "basic familarity",
      "creating server",
      "connecting to db",
      "cors",
      "ENV",
      "integretion with express",
    ],
  },
  {
    id: "EXPRESS",
    alt: "EXPRESS JS LOGO SVG",
    title: "EXPRESS JS",
    icon: "Express",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "faster server side development",
      "REST api",
      "middleware",
      "Routing",
      "Templating",
      "Debugging",
    ],
  },
  {
    id: "MONGODB",
    alt: "MONGO DB LOGO SVG",
    title: "MONGO DB",
    icon: "Mongodb",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "basic familarity",
      "CRUD",
      "indexing",
      "querys",
      "data model",
      "mongodb atlas",
      "mongoose",
    ],
  },
  {
    id: "NEXT",
    alt: "NEXT JS LOGO SVG",
    title: "NEXT JS",
    icon: "Next",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "Server-side rendering (SSR)",
      "Static site generation (SSG)2",
      "Incremental static regeneration (ISR)",
      "Image optimization",
      "Routing",
      "Dynamic routing",
      "Data fetching",
      "Server actions",
    ],
  },
  {
    id: "GIT",
    alt: "GIT LOGO SVG",
    title: "GIT",
    icon: "Git",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "version control",
      "branching and merging",
      "staging and committing",
      "pushing and pulling",
      "collaboration",
      "merge and rebase",
      "resolving conflicts",
    ],
  },
  {
    id: "XD",
    alt: "ADOBE XD LOGO SVG",
    title: "ADOBE XD",
    icon: "Xd",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "fundamentals",
      "assets",
      "components",
      "prototypes",
      "exporting design to code",
    ],
  },
  {
    id: "AI",
    alt: "ADOBE ILLUSTRATOR LOGO SVG",
    title: "A-ILLUSTRATOR",
    icon: "Ai",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "basic familarity",
      "basic tools",
      "complex shape and logo design",
    ],
  },
  {
    id: "AE",
    alt: "ADOBE AFTER EFFECT LOGO SVG",
    title: "A-AFTER EFFECT",
    icon: "Ae",
    description: "Node  asr qwer fdsaf asfgaste wegfsadf sdfwef saefsadf asdf",
    features: [
      "fundamentals",
      "basic tools",
      "motion tracking",
      "masking",
      "simple projects",
    ],
  },
];
