"use client";
import "./globals.css";
import AppProviders from "@/providers/AppProviders";
import { Header, Footer, ContactModel, ProjectFeaturesModel, ProjectImageModel } from "@/components";
import { useEffect, useState } from "react";
import LoaderCube from "@/components/loader/LoaderCube";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  








   const [loading, setLoading] = useState(true);

   useEffect(() => {
     const timer = setTimeout(() => {
       setLoading(false);
     }, 700);
     return () => clearTimeout(timer);
   }, []);

  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
      </head>
      <body
        className={`flex flex-col bg-bg-primary-light dark:bg-bg-primary-dark relative transition-colors duration-1000`}
      >
        {loading ? (
          <div className="h-[100svh] grid place-items-center">
            <LoaderCube />
          </div>
        ) : (
          <AppProviders>
            <Header />
            <ProjectImageModel />
            <ProjectFeaturesModel />
            <ContactModel />
            {children}
            <Footer />
          </AppProviders>
        )}
      </body>
    </html>
  );
}
