import "./globals.css";
import AppProviders from "@/providers/AppProviders";
import { Metadata } from "next";
import LayoutContent from "@/components/layout/LayoutContent";

// FIX--meaning full metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="robots" content="noindex"></meta>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
      </head>
      <body
        className={`flex flex-col bg-bg-primary-light dark:bg-bg-primary-dark relative transition-colors duration-700`}
      >
        <AppProviders>
          <LayoutContent>{children}</LayoutContent>
        </AppProviders>
      </body>
    </html>
  );
}
